# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketKurlyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarketKurlyApp
  pod 'Alamofire'
  pod 'Then'
  pod 'Kingfisher'
  pod 'DLRadioButton'  # 회원가입때 라디오버튼
  pod 'XLPagerTabStrip'  # 홈화면 카테고리별 스와이프
  pod 'ExpyTableView'  # 카테고리화면 테이블 확장
  pod "GSMessages"  # 로그인 팝업알림창
  pod "GMStepper"  # 구매 스탬프 변경
  pod 'DropDown' # 정렬 선택 드롭다운
end
